# Generated by `luarocks nix lua-json`
# 2025-11-14
{ buildLuarocksPackage, fetchFromGitHub, fetchurl, luaOlder }:
buildLuarocksPackage {
  pname = "lua-json";
  version = "1.0.0-1";
  knownRockspec = (fetchurl {
    url = "mirror://luarocks/lua-json-1.0.0-1.rockspec";
    sha256 = "1rb2jvpwf4jk3mfm9mlf7gdlx83lyxqdh0s6m2c8qhjycbyhrc5w";
  }).outPath;
  src = fetchFromGitHub {
    owner = "neoxic";
    repo = "lua-json";
    rev = "1.0.0";
    hash = "sha256-qmxQKbCy5gdOY242tFoPHzS1zbVOj1iSC+hmFzEjRLM=";
  };

  disabled = luaOlder "5.1";

  meta = {
    homepage = "https://github.com/neoxic/lua-json";
    description = "JSON encoding/decoding module for Lua";
    license.fullName = "MIT";
  };
}
